services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - .:/app
    depends_on:
      - json-server
    environment:
      - NODE_ENV=developmentk
  json-server:
    image: clue/json-server
    ports:
      - '3000:80'
    volumes:
      - ./mock-data/db.json:/data/db.json
